### ISSUE TITLE
ballerina 1.0 has dropped

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-ballerina#19]
update the runtime to pick up 1.0

**Comment by whitetigle** [comment]
Hi, any idea if this is going to be updated to 1.x? 
Thanks!

**Comment by rabbah** [comment]
We welcome contributions. There’s no timeline for when this will be updated as of now.

**Comment by whitetigle** [comment]
Unfortunately, I'm not a user of Ballerina. In fact, I just wanted to 
try it using a function so I'm afraid I won't be able to help you with 
that.

Thanks  :)

**Comment by dgrove-oss** [comment]
Closing as won't do.  Archiving the repository
